config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'home#index'

  get :csvs, to: 'csvs#index'
  post :csvs, to: 'csvs#create'
  get 'csvs/:id', to: 'csvs#show', as: :csv

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  delete :logout, to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :csv, optional: true

  validates :uuid, presence: true, uniqueness: true
end

app/models/csv.rb
class Csv < ApplicationRecord
  mount_uploader :file, CsvUploader

  belongs_to :user
  has_many :books

  def send_request
    uri = URI('https://eohs8u7hch4yian.m.pipedream.net')
    req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')

    req.body = {
      'send_from': Rails.env,
      's3_url': file.url
    }.to_json

    Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == 'https') do |http|
      http.request(req)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :csvs

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  helper_method :current_user

  before_action :redirect_to_root

  def logged_in?
    !!session[:user_id]
  end
  
  def current_user
    @current_user ||= set_current_user
  end

  def set_current_user
    @current_user = logged_in? ? User.find(session[:user_id]) : nil
  end

  def redirect_to_root
    redirect_to root_path, notice: 'You must be logged in to access that page.' unless logged_in?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/csvs_controller.rb
class CsvsController < ApplicationController
  def index
    @csvs = current_user.csvs.all
  end

  def create
    books = []
    CSV.foreach(params[:file]).each do |row|
      (title, author, date_published, uuid, publisher_name) = *row
      date = date_published.to_date
      book = Book.new(title: title, author: author, date_published: date, uuid: uuid, publisher_name: publisher_name)

      if book.valid?
        books << book
      else
        raise book.errors.first.full_message
      end
    end
    # Upload the CSV to S3
    csv = current_user.csvs.create(file: params[:file])
    csv.send_request

    # Associate the books with the CSV
    books.each do  |book| 
      book.csv = csv 
      book.save
    end

    redirect_to csvs_path
  rescue StandardError => e
    redirect_to csvs_path, error: e.message
  end

  def show
    @csv = Csv.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :redirect_to_root, only: [:index]

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_to_root, only: [:new, :create, :destroy]

  def new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user&.authenticate(user_params[:password])
      session[:user_id] = @user.id

      redirect_to csvs_path
    else
      redirect_to new_session_path, error: 'Wrong email or password.'
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_to_root, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id

    redirect_to csvs_path
  rescue ActiveRecord::RecordInvalid => e
    redirect_to new_user_path, error: e.message
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/csvs_helper.rb
module CsvsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/csvs/create.html.erb
<h1>Csvs#create</h1>
<p>Find me in app/views/csvs/create.html.erb</p>

app/views/csvs/index.html.erb
<%= form_with url: '/csvs', method: :post, class: 'text-center' do |form| %>
  <%= form.label :csv, "Upload a new CSV:", class: 'label block m-5' %>
  <%= form.file_field :file, required: true, accept: '.csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel', class: 'file-input w-full max-w-xs m-3' %>
  <%= form.submit 'Save', class: 'btn' %>
<% end %>

<% if @csvs.size > 0 %>
  <h1 class="text-center text-2xl mt-10">All your csvs</h1>
<% else %>
  <h1 class="text-center text-2xl mt-10">No CSVs yet</h1>
<% end %>

<% @csvs.each do |csv| %>
  <%= link_to csv_path(csv), id: "csv-#{csv.id}", class: 'flex justify-between items-center m-6 p-6 block rounded-lg border shadow-md bg-gray-800 border-gray-700 hover:bg-gray-100 hover:bg-gray-700' do %>
    <div>
      <h5 class="whitespace-nowrap text-ellipsis overflow-hidden mb-2 text-2xl font-bold tracking-tight text-white"><%= "CSV #{csv.id}" %></h5>
      <p class="font-normal text-gray-400"><%= csv.books.size %> books</p>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 15l3-3m0 0l-3-3m3 3h-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  <% end %>
<% end %>

app/views/csvs/show.html.erb
<div class="text-center my-10">
  <div>S3 link:</div>
  <%= link_to @csv.file.identifier, @csv.file.url %>
</div>

<div class="overflow-x-auto">
  <table class="table w-full">
    <thead>
      <tr>
        <th></th>
        <th>Book title</th>
        <th>Book author</th>
        <th>Date published</th>
        <th>Unique identifier</th>
        <th>Publisher name</th>
      </tr>
    </thead>
    <tbody>
      <% @csv.books.each_with_index do |book, index| %>
        <tr>
          <th><%= index + 1 %></th>
          <th><%= book.title %></th>
          <td><%= book.author %></td>
          <td><%= book.date_published %></td>
          <td><%= book.uuid %></td>
          <td><%= book.publisher_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<section class="min-h-screen">
  <h1 class="text-center" style="font-size: 100px;">Welcome to CSVs!</h1>
  <p class="text-center text-2xl">A parser for books CSVs</p>
</section>

app/views/layouts/_navbar.html.erb
<nav class="bg-transparent border-gray-200 p-5 sm:p-6 rounded dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

    <%= link_to root_path, class: 'flex items-center hover:no-underline' do %>
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Csvs</span>
    <% end %>

      <% if current_user %>
        <ul class="flex bg-transparent">
          <li>
            <%= link_to 'Dasboard', csvs_path, class: 'btn btn-ghost' %>
          </li>
          <li>
            <%= button_to 'Sign out', logout_path, method: :delete, class: 'btn btn-ghost' %>
          </li>
        </ul>

      <% else %>
        <ul class="flex bg-transparent">
          <li>
            <%= link_to 'Sign in', new_session_path, class: 'btn btn-ghost' %>
          </li>
          <li>
            <%= link_to 'Sign up', new_user_path, class: 'btn' %>
          </li>
        </ul>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csvs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto max-w-[1200px]">
      <header>
        <%= render partial: 'layouts/navbar' %>
      </header>

      <%# Flash notices %>
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %> shadow-lg">
          <div>
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span><%= msg %></span>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_links.html.erb
<section class="mx-auto my-10 rounded-lg shadow p-10 max-w-lg border-gray-600 border-solid border">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Sign in", new_session_path, class: 'btn btn-ghost' %><br />
  <% end %>

  <%- if controller_name != 'users' %>
    <%= link_to "Sign up", new_user_path, class: 'btn btn-ghost' %><br />
  <% end %>
</section>

app/views/users/new.html.erb
<div class="mx-auto my-10 rounded-lg shadow p-10 max-w-lg border-gray-600 border-solid border">
  <h1 class="text-center text-2xl mb-6"><%= t('.sign_up') %></h1>
  <%= form_for User.new, url: users_path do |f| %>

    <div class="mb-6">
      <%= f.label :email, class: 'font-medium' %>
      <%= f.email_field :email, class: 'input' %>
    </div>

    <div class="mb-6">
      <%= f.label :password, class: 'font-medium' %>
      <%= f.password_field :password, class: 'input' %>
    </div>

    <div class="actions">
      <%= f.submit 'Sign up', class: 'my-2 text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800' %>
    </div>
  <% end %>
</div>
<%= render partial: 'shared/links' %>